### ISSUE TITLE
raspberry-pi-px4firmware\cmake\toolchains\Toolchain-arm-bcm2835-linx-gnueabihf-raspbian.cmake

### ISSUE THREAD

**Issue by shawn166888** [crossa/raspberry-pi-px4firmware#2]
bcm2835-linx -> bcm2835-linux
花了我半小时才看到

**Comment by crossa** [comment]
不用了，Debian9下面直接可以用系统自带工具链编译了，不要这个了

**Comment by itstmyi** [comment]
@advulcan 谢谢你这个issue，让我少花了不少时间。

**Comment by itstmyi** [comment]
@crossa 把你多个地方的帖子全拜读了一遍，虽然里面有点小错误，但是让我少走了很多弯路，非常感谢！
